package pojos;
// Generated Jan 27, 2020 4:24:05 PM by Hibernate Tools 4.3.1



/**
 * KaryawanTbl generated by hbm2java
 */
public class KaryawanTbl  implements java.io.Serializable {


     private Integer idKaryawan;
     private String nama;
     private String gender;
     private String alamat;

    public KaryawanTbl() {
    }

    public KaryawanTbl(String nama, String gender, String alamat) {
       this.nama = nama;
       this.gender = gender;
       this.alamat = alamat;
    }
   
    public Integer getIdKaryawan() {
        return this.idKaryawan;
    }
    
    public void setIdKaryawan(Integer idKaryawan) {
        this.idKaryawan = idKaryawan;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


